local Punch = {
    name = "Punch",
    cooldownTime = 0.27,
    maxComboCooldownTime = 0.5,
    maxComboCount = 3,
    comboWindow = 0.5,
    damage = 10,
    penetration = 0,
    maxComboDamage = 20,
    maxComboPenetration = 0,
    hitboxSize = Vector3.new(4, 5, 3),
    hitboxOffset = Vector3.new(0, 0, -2),
    hitboxDuration = 0.27,
    maxComboHitboxDuration = 0.4,
    speedMultiplier = 0.5,
}

return Punch